# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-SearchPath
version:      0.001
version_from: SearchPath.pm
installdirs:  site
requires:
    File::Spec:                    0.8
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
