--- #YAML:1.0
name:                File-SearchPath
version:             0.03
abstract:            Search for a file in an environment variable path
license:             ~
author:              
    - Tim Jenness <tjenness@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Spec:                    0.8
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
