--- #YAML:1.0
name:               File-SearchPath
version:            0.05
abstract:           Search for a file in an environment variable path
author:
    - Tim Jenness <tjenness@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:  0.8
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
